# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171127_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
